# nginx-data.conf — sirve la ontología y los archivos .mat
# Usado por el contenedor "ontology".

events {}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {    
        listen 80;
        server_name _;

        location /ontology/ {
            alias /usr/share/nginx/html/ontology/;
            autoindex on;          # archivos suelto .ttl y docs 
            autoindex_exact_size off;
            autoindex_localtime on;
        }

        location /data/ {
            alias /usr/share/nginx/html/data/;
            autoindex on;          # listado de los .mat
            autoindex_exact_size off;
            autoindex_localtime on;
        }
    }
}