# nginx-data.conf — sirve la ontología y los archivos .mat
# Usado por el contenedor "ontology".

events {}

http {
    server {
        listen 80;
        server_name _;

        autoindex off;

        location /ontology/ {
            alias /usr/share/nginx/html/ontology/;
        }

        location /data/ {
            alias /usr/share/nginx/html/data/;
        }
    }
}
